left-curve/left-curve

- crates/vm/wasm/src/environment.rs
- crates/vm/wasm/src/error.rs
- crates/vm/wasm/src/imports.rs
- crates/vm/wasm/src/memory.rs
- crates/vm/wasm/src/vm.rs
- Merge `ContextData` and `Environment` into one struct:
Old:
```rust
struct ContextData {
pub storage: StorageProvider,
pub querier: QuerierProvider<WasmVm>,
pub iterators: HashMap<i32, Iterator>,
pub next_iterator_id: i32,
pub gas_tracker: GasTracker,
wasmer_instance: Option<NonNull<Instance>>,
}
struct Environment {
memory: Option<Memory>,
data: Arc<RwLock<ContextData>>,
}
```
New:
```rust
struct Environment {
pub storage: StorageProvider,
pub querier: QuerierProvider<WasmVm>,
pub gas_tracker: GasTracker,
iterators: HashMap<i32, Iterator>,
next_iterator_id: i32,
wasmer_memory: Option<Memory>,
wasmer_instance: Option<NonNull<Instance>>,
}
```
- Some renamings
- Add some comments
> Improvements to WasmVm

- Cargo.lock
- crates/crypto/Cargo.toml
- crates/crypto/src/ed25519.rs
- crates/crypto/src/identity_digest.rs
- crates/crypto/src/secp256k1.rs
- crates/crypto/src/secp256r1.rs
- crates/crypto/tests/rootberg.rs
- crates/crypto/tests/wycheproof.rs
- Inconsistent use of terminology: 1) sometimes we use `prehash_msg` to mean the prehash and `msg` to mean the hash; 2) sometimes we use `msg` to mean the prehash and `msg_hash` to mean the hash.
Fix: Now we consistently use (2).
- For Ed25519, we first hash the message with `sha2_256`, then call `sk.sign`. This is incorrect, because `sk.sign` performs a SHA2-512 hash before signing, so we effectively hash twice.
Fix: The correct way is to first do `sha2_512`, then call `sk.sign_digest`. This involves adding the "digest" feature when importing ed25519-dalek, and adding a new `Identity512` type.
- For `ed25519_batch_verify`, there is only `sk.verify_batch` which takes a list of _prehash_ messsages; there isn't a method that takes a batch of _hashed_ messages. Therefore, unlike other …
> Crypto fixes

- crates/app/src/shared.rs
- crates/vm/wasm/src/iterator.rs
Discovered by @Rhaki 
The bug exists in `grug_app::SharedIter` and `grug_vm_wasm::Iterator`
When collecting a new batch, when updating the `self.min` bound, it should use `extend_one_byte` instead of `increment_last_byte`.
> Fix a bug in shared iterator

- Cargo.lock
- crates/app/src/gas.rs
- crates/app/src/traits.rs
- crates/types/src/macros.rs
- crates/vm/rust/Cargo.toml
- crates/vm/rust/README.md
- crates/vm/rust/src/contract.rs
- crates/vm/rust/src/error.rs
- crates/vm/rust/src/traits.rs
- crates/vm/rust/src/vm.rs
- crates/vm/wasm/src/environment.rs
- crates/vm/wasm/src/vm.rs
- Use `&'static str` instead of `String` for function names
- Adjust `grug_vm_rust::Contract` method signatures:
- Return `VmResult<GenericResult<T>>` instead of `GenericResult<T>`. The `VmResult` means an error happened at the VM level; the `GenericResult` means an error happened inside the contract.
- Take `msg: &[u8]` instead of `msg: Json`. This prevents some unnecessary serializations.
- Gracefully handle the case where a contract doesn't implement a function. (Added: `VmError::FunctionNotFound`)
- Handle the case where the caller attempts to call an unknown/unsupported function. (Added: `VmError::UnknownFunction`)
- Handle the case where the contract is not found with the given index. (Added: `VmError::ContractNotFound`)
> Improvements to RustVm

- crates/storage/src/key.rs
- crates/types/src/address.rs
- crates/types/src/db.rs
- crates/types/src/error.rs
- crates/types/src/hash.rs
- crates/types/src/serializers.rs
1. Add method to serialize to / deserialize from JSON strings
2. Add the name of the codec to `StdError::{Serialize,Deserialize}` error messages
> Add JSON string methods; more details to error messages

- crates/app/src/app.rs
- crates/testing/tests/queries.rs
- crates/types/src/imports.rs
- crates/types/src/query.rs
1. FFI can be a bottleneck in performance. If a contract needs to make multiple queries, it may be more efficient to bundle them into a single FFI call. 
2. This also allows clients to make only a single HTTP query to the node.
> Multi query

- crates/testing/src/account.rs
- crates/testing/src/suite.rs
- crates/testing/tests/account.rs
Our app uses different sign bytes than the mock account in this repo, so in order to use the `TestSuite` in the app, we need to abstract test accounts as a trait.
> Signer trait

- bin/src/tx.rs
- crates/app/src/app.rs
- crates/app/src/execute.rs
- crates/client/src/client.rs
- crates/testing/src/suite.rs
- crates/testing/tests/cron.rs
- crates/types/src/app.rs
- crates/types/src/tx.rs
Introduces a `ConfigUpdates` struct, so that when updating a config it's no longer necessary to input the entire config.
> Better config updates

- contracts/account/src/execute.rs
- contracts/account/src/query.rs
- contracts/account/src/state.rs
- crates/storage/src/counter.rs
- Allow user to specify the starting value and step size for the counter.
- Return both the old and new value in the `Counter::increment` method.
- Add a `Counters` (plural) type which is a wrapper over a `Map`
> Better counter

- crates/storage/src/codec.rs
- crates/storage/src/index/map.rs
- crates/storage/src/index/multi.rs
- crates/storage/src/index/unique.rs
- crates/types/src/error.rs
- `UniqueIndex::index_map` now stores a mapping of IK => PK (previously it stores IK => T). This allows us to give an IK and find the corresponding PK (previously not possible).
- The indexer function of `UniqueIndex` now also takes the PK (previously only takes T).
- Adds an error type `StdError::DuplicateData`
> UniqueIndex redone

- Cargo.lock
- contracts/bank/src/types.rs
- contracts/tester/src/execute.rs
- contracts/tester/src/types.rs
- crates/macros/src/lib.rs
- crates/macros/src/query.rs
- crates/std/tests/queries.rs
- crates/testing/Cargo.toml
- crates/testing/src/suite.rs
- crates/testing/tests/queries.rs
- crates/types/src/imports.rs
- crates/types/src/query.rs
- crates/vm/wasm/tests/wasm_vm.rs
`gurg_macro::Query` is a new `proc_macro_derive` that automatize some traits implementation and Struct generation for improve the developer experience for execute query between contracts. 
Usage:
```rust
#[derive(grug::Query)]
#[grug::derive(serde)]
pub enum QueryMsg {
#[returns(ConfigResponse)
Config {}
#[returns(StateResponse)
State(StateRequest)
}
``` 
`grug::Query` check each enum variant and if the variant is `syn::Fields::Named` (like `Config {}`), a new `Struct` called `ConfigRequest` is created with the same parameters (no one in this case).
```rust
pub struct ConfigRequest {}
```
Then for each `Request` `Struct` the macro impl `impl From<#struct_name> for #name` and the trait `QueryResponseType` for mapping `Request => Response`.
Also QuerierWrapper expose a new method called …
> feat: `#[derive(grug::QueryRequest)]`

- crates/app/src/gas/storage.rs
- crates/jellyfish-merkle/src/bitarray.rs
- crates/storage/src/bound.rs
- crates/storage/src/counter.rs
- crates/storage/src/index/map.rs
- crates/storage/src/index/multi.rs
- crates/storage/src/index/unique.rs
- crates/storage/src/key.rs
- crates/storage/src/map.rs
- crates/storage/src/prefix.rs
- crates/storage/src/set.rs
As we discussed, the word "key" can have two meanings:
- a database key
- a cryptographic key
which can be confusing.
`PrimaryKey` can be a better naming, because it's commonly used in database context, and aligns with CosmWasm.
> Rename `Key` to `PrimaryKey`

- crates/app/src/execute.rs
- crates/client/src/client.rs
- crates/client/src/genesis_builder.rs
- crates/db/disk/src/db.rs
- crates/db/memory/src/db.rs
- crates/jellyfish-merkle/src/node.rs
- crates/jellyfish-merkle/src/proof.rs
- crates/jellyfish-merkle/src/tree.rs
- crates/testing/src/builder.rs
- crates/types/src/address.rs
- crates/types/src/hash.rs
- crates/types/src/hashers.rs
Replace `grug::{hash160,hash256}` functions with the `HashExt` trait.
This is the same as #121, but we split into two PRs: one for hashes, one for serializers.
> Replace hasher functions with extension trait

- crates/crypto/src/ed25519.rs
- crates/ffi/src/imports.rs
- crates/types/src/imports.rs
- crates/vm/rust/src/api.rs
- crates/vm/wasm/src/imports.rs
1. Fixes a memory bug related to `Region::build`
2. Rename the input parameter `msgs_hash` to `prehash_msgs`, since this function takes the preimages.
> Fixes to ed25519 batch verify

- contracts/taxman/src/execute.rs
- crates/client/examples/build_genesis.rs
- crates/std/tests/queries.rs
- crates/testing/tests/account.rs
- crates/testing/tests/cron.rs
- crates/testing/tests/queries.rs
- crates/testing/tests/taxman.rs
- crates/types/src/bytearray.rs
- crates/types/src/error.rs
- crates/types/src/lib.rs
- crates/types/src/math/traits.rs
- crates/types/src/math/udec.rs
- crates/types/src/non_zero.rs
- crates/vm/rust/tests/transfer.rs
- crates/vm/wasm/tests/tester.rs
- crates/vm/wasm/tests/transfer.rs
`NonZero::new` method now errors instead of panics in case a zero value is provided.
Also, implement necessary traits such that `NonZero<T>` can be used in messages or storage.
> Improvements to NonZero

- crates/vm/wasm/src/vm.rs
`WasmInstace` now proivde a `use_env_mut` function that reduce the verbose in the code for using `& mut env`
```rust
// Old
let mut fe_mut = self.fe.clone().into_mut(&mut self.store);
let (env, mut store) = fe_mut.data_and_store_mut();
// New
self.use_env_mut(|env, store| { 
...
}
```
>  C-WasmVm-2: Instance

- crates/storage/src/index/map.rs
- crates/storage/src/map.rs
- crates/storage/src/path.rs
Similar to standard library's `Option::take`.
Basically, read the value, delete it, and return the value.
> Add `take` method to `Item` and `Map`

- CONTRIBUTING.md
- crates/math/src/fixed_point.rs
- crates/math/src/lib.rs
- crates/math/src/udec.rs
- crates/storage/src/key.rs
- crates/types/src/macros.rs
- docs/guides/math.md
Removed `const S: u32` as generic param for `Udec`, hardcoded to `18`
> M1 - Simplify `Udec`

- dango/bank/src/execute.rs
- dango/taxman/src/execute.rs
- dango/token-factory/src/execute.rs
- grug/math/src/is_zero.rs
- grug/math/src/sign.rs
- grug/mock-taxman/src/execute.rs
- grug/testing/tests/taxman.rs
- grug/types/src/coin_pair.rs
- grug/types/src/coins.rs
Using `number.is_non_{zero,negative,positive}` is exactly the same as using `!number.is_{zero,negative,positive}`, but imo it's more readable.
> feat(grug): add `is_non_{zero,negative,positive}` methods

- Cargo.lock
- dango/account-factory/src/execute.rs
- dango/account-factory/src/query.rs
- dango/genesis/src/lib.rs
- dango/testing/benches/benchmarks.rs
- dango/testing/src/account.rs
- dango/testing/tests/onboarding.rs
- dango/testing/tests/safe.rs
- grug/app/Cargo.toml
- grug/app/src/abci.rs
- grug/app/src/execute.rs
- grug/client/Cargo.toml
- grug/client/src/client.rs
- grug/db-disk/src/db.rs
- grug/jellyfish-merkle/Cargo.toml
- grug/jellyfish-merkle/src/bitarray.rs
- grug/jellyfish-merkle/src/proof.rs
- grug/jellyfish-merkle/src/tree.rs
- grug/std/tests/queries.rs
- grug/storage/src/key.rs
- grug/testing/src/account.rs
- grug/testing/src/builder.rs
- grug/testing/src/suite.rs
- grug/types/src/address.rs
- grug/types/src/app.rs
- grug/types/src/hash.rs
- grug/types/src/hashers.rs
- grug/vm-wasm/benches/benchmarks.rs
- sdk/packages/sdk/src/actions/public/computeAddress.ts
Delete the following methods:
- `Addr::from_array`
- `Hash::{from_array,into_array,into_vec}`
Because you can already do the same with methods such as `from_inner`, `into_inner`.
Ideally, there is only one way to do something.
I didn't remove these in previous PRs because I want to keep diffs small.
> refactor(grug): remove excess methods

- dango/testing/benches/benchmarks.rs
- dango/testing/tests/amm.rs
- dango/testing/tests/onboarding.rs
- dango/testing/tests/safe.rs
- dango/testing/tests/token_factory.rs
- grug/std/tests/queries.rs
- grug/testing/src/account.rs
- grug/testing/src/builder.rs
- grug/testing/src/suite.rs
- grug/testing/tests/account.rs
- grug/testing/tests/cron.rs
- grug/testing/tests/queries.rs
- grug/testing/tests/taxman.rs
- grug/types/src/app.rs
- grug/types/src/result.rs
- grug/vm-rust/tests/transfer.rs
- grug/vm-wasm/tests/tester.rs
- grug/vm-wasm/tests/transfer.rs
- `ResultExt` now require associated type over generics;
- `TxOutcome` impls`ResultExt`;
- `Outcome` impls`ResultExt`;
- remove `ResultExt` for `GenericResult`.
- `TestAccounts` now are a wrapper struct over `HashMap<&'static str, TestAccount>`;
- `instantiate` methods now return `InstantiateOutcome`;
- `upload` methods now return `UploadOutcome`;
- `upload_and_instantiate` methods now return `UploadAndInstantiateOutcome`.
> feat(grug): Result `Outcome` and `Suite` improvements

- grug/client/src/client.rs
- grug/testing/src/suite.rs
> refractor(grug): use `Option<&str>` instead of generic for label

- dango/taxman/src/execute.rs
- dango/types/src/taxman.rs
- grug/mock-taxman/src/execute.rs
- grug/mock-taxman/src/exports.rs
- grug/mock-taxman/src/types.rs
- sdk/packages/encoding/src/binary.spec.ts
- sdk/packages/types/src/index.ts
- sdk/packages/types/src/tx.ts
Consistent naming. Prefer a single verb over a phrase.
> refactor: rename UpdateConfig to Configure

- dango/account-factory/src/execute.rs
- dango/bank/src/execute.rs
- grug/mock-bank/src/execute.rs
- grug/storage/src/index/map.rs
- grug/storage/src/item.rs
- grug/storage/src/map.rs
- grug/storage/src/path.rs
Add the following methods to:
- `Path`
- `Item`
- `Map`
- `IndexedMap`
| method       | input       | output      |
| ------------ | ----------- | ----------- |
| `update`     | `T`         | `T`         |
| `may_update` | `Option<T>` | `T`         |
| `modify`     | `T`         | `Option<T>` |
| `may_modify` | `Option<T>` | `Option<T>` |
> feat(grug): more storage update methods

- README.md
- docker-compose.yml
- docker/devnet/Dockerfile
- justfile
Ran into some issues when trying to run devnet and frontend. Fixes applied:
- Add prerequisite to have Node.js v20.18.0. I was on 16 or 18 (can't recall) and it only worked once upgraded to 20.18.0. Perhaps some lesser version works, but not sure.
- Allow CORS from any origin in devnet. Otherwise frontend can't connect to RPC node in docker container.
- Add docker compose file for easy launch of devnet with `docker compose up` and `docker compose rm` to reset.
> fix: small build fixes

- grug/storage/src/lib.rs
- grug/storage/src/prefixer.rs
- grug/storage/src/primary_key.rs
Closes: #256
This file is too long, and contains two traits.
We split it into two files, each contains one trait.
Also add some docs and prettify some macros.
> refactor(grug): split `storage/src/key.rs` into two smaller files

- dango/auth/src/lib.rs
- dango/testing/benches/benchmarks.rs
- dango/testing/src/account.rs
- dango/types/src/auth.rs
- sdk/packages/connect-kit/src/connectors/passkey.ts
- sdk/packages/core/src/signers/privateKey.ts
We've added the sender to `SignDoc` struct to enhance user protection against replay attacks. Previously, since the same key could be used across different accounts, there was a risk of the same transaction being submitted in a particular sequence on another account. By including the sender, we ensure the transaction cannot be reused in a different account, even with the same key.
> feat(dango): signdoc with sender

- grug/app/src/app.rs
- grug/app/src/proposal.rs
- grug/jellyfish-merkle/src/tree.rs
Hello :octocat: 
This includes a test from a scenario I found with [Quint](https://quint-lang.org) where, after some combination of operations, we end up with a leaf node being saved both on bit `0` and `010`.
> fix(grug): extra node being saved in JMT subtree creation

- sdk/packages/config/ts/common.json
- sdk/packages/config/tsup/common.json
- sdk/packages/connect-kit/tsconfig.json
- sdk/packages/core/tsconfig.json
- sdk/packages/crypto/tsconfig.json
- sdk/packages/encoding/tsconfig.json
- sdk/packages/react/tsconfig.json
- sdk/packages/utils/tsconfig.json
- ui/portal/tsconfig.json
- ui/shared/tsconfig.json
- ui/workers/mock-ibc/tsconfig.json
We're adding the composite and reference options into the tsconfig. When developing this makes possible to refresh the types right at the moment. Before it was necessary to restart VS Code ts-server in order to get the latest version.
We disable composite option in tsup, it uses rollup-plugin-dts to output .d.ts files and doesn't support composite.
> feat(sdk): update ts reference real time

- .github/workflows/quint.yml
- .markdownlint.json
- .vscode/settings.json
- grug/jellyfish-merkle/spec/README.md
- grug/jellyfish-merkle/spec/docs/grug_ics23.md
- grug/jellyfish-merkle/spec/docs/invariants.md
- grug/jellyfish-merkle/spec/docs/proof_types.md
- grug/jellyfish-merkle/spec/docs/proofs.md
- grug/jellyfish-merkle/spec/docs/simulation_and_model_checking.md
- grug/jellyfish-merkle/spec/docs/tree_manipulation.md
- grug/jellyfish-merkle/spec/quint/apply_fancy.qnt
- grug/jellyfish-merkle/spec/quint/apply_simple.qnt
- grug/jellyfish-merkle/spec/quint/completeness.qnt
- grug/jellyfish-merkle/spec/quint/grug_ics23.qnt
- grug/jellyfish-merkle/spec/quint/hashes.qnt
- grug/jellyfish-merkle/spec/quint/proofs.qnt
- grug/jellyfish-merkle/spec/quint/spells/commonSpells.qnt
- grug/jellyfish-merkle/spec/quint/spells/rareSpells.qnt
- grug/jellyfish-merkle/spec/quint/test/apply_simple_test.qnt
- grug/jellyfish-merkle/spec/quint/test/node_test.qnt
- grug/jellyfish-merkle/spec/quint/tla/README.md
- grug/jellyfish-merkle/spec/quint/tla/setupA/changes.patch
- grug/jellyfish-merkle/spec/quint/tla/setupB/changes.patch
- grug/jellyfish-merkle/spec/quint/tree.qnt
- grug/jellyfish-merkle/spec/quint/utils.qnt
- grug/jellyfish-merkle/spec/scripts/quint-forall.sh
- run formatters (editorconfig and markdown-all-in-one)
- address markdownlint issues
> spec: run formatter and address linter issues in JMT spec

- grug/storage/src/prefixer.rs
- grug/storage/src/primary_key.rs
implement `PrimaryKey` and `Prefixer` traits for `Bounded` and `LengthBounded`.
we don't need this for now, but it's a good to have.
> feat(grug): implement storage key traits for bounded types

- Cargo.lock
- Cargo.toml
rust-rocksdb finally released 0.23, so we don't need to use our fork any more.
> update rust-rocksdb to official release

- .github/workflows/rust.yml
- Cargo.lock
- grug/app/Cargo.toml
- grug/app/src/traits/db.rs
- grug/db/disk/Cargo.toml
- grug/db/disk/src/db.rs
- grug/db/disk/src/ics23.rs
- grug/db/disk/src/lib.rs
- grug/db/memory/Cargo.toml
- grug/db/memory/src/db.rs
- grug/jellyfish-merkle/Cargo.toml
- grug/jellyfish-merkle/src/lib.rs
we no longer use IBC, so ICS-23 related stuff can be made optional.
> refactor(grug): make ICS-23 optional

- grug/app/src/app.rs
these linter warnings can be found by:
```
cargo clippy -p grug-app --no-default-features
```
since `abci` and `tracing` features are default and always enabled, we weren't able to catch them earlier.
> lint(grug): fix or ignore a few linter warnings in grug-app

- Cargo.lock
- grug/app/Cargo.toml
- grug/app/src/app.rs
- grug/jellyfish-merkle/Cargo.toml
use the following commands to make sure:
```
cargo clippy -p grug-app --no-default-features
cargo clippy -p grug-app --no-default-features --features abci
cargo clippy -p grug-app --no-default-features --features tracing
cargo clippy -p grug-app --no-default-features --features abci,tracing
```
> lint(grug): more fixes related to optional dependencies in grug-app

- dango/account/margin/src/execute.rs
- dango/dex/src/execute.rs
- dango/types/src/account/margin.rs
- dango/types/src/dex.rs
- dango/types/src/warp.rs
- dango/warp/src/execute.rs
- grug/macros/src/event.rs
- grug/macros/src/lib.rs
- grug/types/src/events.rs
- grug/types/src/events/contract_event.rs
- grug/types/src/response.rs
- hyperlane/grug/hooks/merkle/src/execute.rs
- hyperlane/grug/mailbox/src/execute.rs
- hyperlane/grug/types/src/hooks/merkle.rs
- hyperlane/grug/types/src/mailbox.rs
Instead of manually adding the string type of a event into the `Response` via `Response::add_event(ty: impl Into<String>, event: impl Serialize)`,  `add_event` require now a single param `E: impl AsContractEvent`
```rust
pub trait AsContractEvent: Serialize {
const NAME: &'static str;
}
```
The trait `AsContractEvent` can be implemented with a new `proc_macro_attribute`
```rust
#[grug::derive(Serde)]
#[grug::event("handle")]
pub struct Handle {
pub recipient: Addr32,
pub token: Denom,
pub amount: Uint128,
}
```
> feat(grug): Contract Event Trait

- dango/dex/src/execute.rs
- dango/dex/src/query.rs
- dango/dex/src/state.rs
- dango/genesis/examples/build_genesis.rs
- dango/genesis/src/lib.rs
- dango/testing/src/setup.rs
- dango/testing/tests/dex.rs
- dango/types/src/dex.rs
necessary 1) for preventing spam orders, and 2) for implementing passive liquidity pools.
see #439
> feat(dango): permissioned creation of DEX pairs

- dango/bank/src/execute.rs
- dango/dex/src/execute.rs
- dango/indexer/sql/src/hooks.rs
- dango/testing/tests/lending.rs
- dango/types/src/bank/msgs.rs
- grug/app/src/app.rs
- grug/app/src/execute/execute.rs
- grug/app/src/execute/instantiate.rs
- grug/app/src/execute/transfer.rs
- grug/app/src/macros.rs
- grug/mocks/bank/src/execute.rs
- grug/mocks/bank/src/exports.rs
- grug/types/src/bank.rs
- grug/types/src/events/builder.rs
- grug/types/src/events/flat.rs
- grug/types/src/events/flatten.rs
- grug/types/src/events/nested.rs
- grug/types/src/tx.rs
this PR makes `grug_types::Message::Transfer` multi-send.
removes `dango_types::bank::Message::BatchTransfer` because it's no longer needed.
> feat(grug): native multi send

- dango/auth/src/lib.rs
- dango/client/src/signer.rs
we forgot to check `ctx.chain_id == metadata.chain_id`
> fix(dango/auth): ensure chain ID matches

- grug/app/src/query_app.rs
- indexer/httpd/src/graphql/query/grug.rs
- indexer/httpd/src/graphql/types.rs
- indexer/httpd/src/graphql/types/store.rs
- `queryApp` 
- height is now optional:
- proof is removed (proof is supported only for `queryStore`).
- `queryStore`:
- return a dedicated schema with field in B64;
- key is now in B64.
- `simulate`
- removed height (cannot simulate at past height);
- proof is removed (proof is supported only for `queryStore`).
> refractor(graphql): Better queries interface

- dango/dex/src/execute.rs
no need to call `transfer` if the coins are empty.
> fix(dango/dex): only transfer if refunds in non-empty

- Cargo.lock
- dango/auth/Cargo.toml
- dango/auth/src/lib.rs
- dango/client/src/signer.rs
- dango/testing/Cargo.toml
- dango/testing/src/account.rs
- dango/testing/src/crypto.rs
- dango/testing/tests/session_key.rs
- dango/types/Cargo.toml
- dango/types/src/auth.rs
- grug/crypto/src/identity_digest.rs
- grug/mocks/account/Cargo.toml
- grug/mocks/account/src/execute.rs
- grug/mocks/account/src/types.rs
- grug/testing/src/account.rs
- grug/types/src/signer.rs
Follow up to #566 and #567.
This PR adds a new `SignData` trait, so that for each structure that needs to be signed (e.g. `dango_types::auth::SignDoc` and `SessionInfo`) there's a single source of truth on how to convert this structure to raw bytes, and which hash function to use.
> refactor: `SignData` trait

- Cargo.lock
- dango/auth/Cargo.toml
- dango/auth/src/lib.rs
- dango/types/src/account_factory/salts.rs
- dango/types/src/auth.rs
- grug/crypto/src/secp256k1.rs
- grug/types/src/imports/api.rs
Currently we use `Key::Secp256k1` for Ethereum wallet login. This is not ideal, because Ethereum wallets typically don't allow webapps to know the pubkey (however, they do allow webapps to know the address). We circumvent this by prompting the user to sign a signature, and extracting the pubkey from the signature. This is however a bad UX.
This PR adds a new key type `Key::Ethereum` which takes an Ethereum address. In dango-auth, we use `ctx.api.secp256k1_pubkey_recover` to verify the signature.
Now there are 3 variants for `Key` and 3 variants for `Credential`. We require they have the following correspondance:
| Key | Credential | Use Case |
| --- | --- | --- |
| `Key::Ethereum` | `Credential::Eip712` | Ethereum wallet login |
| `Key::Secp256r1` | `Credential::Passkey` | Passkey login | …
> refactor(dango): add ethereum address as a key type

- Cargo.lock
- dango/account/factory/Cargo.toml
- dango/account/factory/src/execute.rs
- dango/account/factory/src/state.rs
- dango/auth/Cargo.toml
- dango/auth/src/lib.rs
- dango/genesis/src/lib.rs
- dango/testing/Cargo.toml
- dango/testing/src/account.rs
- dango/testing/tests/factory.rs
- dango/types/src/account_factory/events.rs
- dango/types/src/account_factory/msg.rs
- dango/types/src/account_factory/salts.rs
- Replace the `secret` in `NewUserSalt` to the `username`.
- In `account_factory::ExecuteMsg::RegisterUser`, user must provide the `NewUserSalt` and a signature signed over the salt.
- Change the `UserRegistered` event (@Rhaki this impacts the Galxe bot)
> refactor(dango): require user signature when onboarding

- Cargo.lock
- dango/auth/src/lib.rs
- dango/testing/Cargo.toml
- dango/testing/tests/multi.rs
require the nonce of an incoming tx to not be too much bigger than the biggest seen nonce so far. this is to prevent a possible DoS attack in a multisig by a rogue member.
> fix(dango/auth): nonce jump check

- Cargo.lock
- hyperlane/isms/multisig/Cargo.toml
- hyperlane/isms/multisig/src/query.rs
This prevents a DoS attack where an attack submits a message with a great amount of signatures.
> fix(hyperlane): add upper limit for number of signatures in ISM metadata

- Cargo.lock
- Cargo.toml
- grug/crypto/benches/benchmarks.rs
most importantly, specify sqlx to be "0.8" instead of just "0", otherwise we have a dependency issue in the bots repo
> chore: bump dependencies
