left-curve/left-curve

crates/vm/wasm/src/environment.rs
crates/vm/wasm/src/imports.rs

See the comments added in `db_write` for rationale.

Fix a bug in storage import methods

---

bin/src/tx.rs
crates/testing/src/builder.rs
crates/testing/src/suite.rs
crates/types/src/binary.rs
crates/types/src/error.rs
crates/types/src/tx.rs
sdk/rust/src/client.rs

Reduces boilerplate when creating `Message`s.

Add constructor methods to `Message`

---

bin/src/query.rs
bin/src/tx.rs
crates/app/src/abci.rs
crates/app/src/app.rs
sdk/js/src/client.ts
sdk/rust/src/client.rs
sdk/rust/src/key.rs
sdk/rust/src/options.rs

Update CheckTx; improvements to the SDK and the CLI

---

Cargo.lock
bin/src/query.rs
bin/src/tx.rs
crates/app/src/app.rs
crates/app/src/execute.rs
crates/app/src/query.rs
crates/app/src/state.rs
crates/client/src/client.rs
crates/storage/Cargo.toml
crates/storage/src/codec.rs
crates/testing/src/suite.rs
crates/testing/tests/cron.rs
crates/types/src/imports.rs
crates/types/src/query.rs
crates/types/src/tx.rs

App config

---

crates/app/src/app.rs
crates/client/src/genesis_builder.rs
crates/testing/src/builder.rs
crates/types/src/app.rs

Allows developer to set app configs during genesis.

Add app configs to genesis state

---

crates/storage/src/item.rs
crates/storage/src/path.rs

Based on https://github.com/left-curve/grug/pull/118#issuecomment-2307173322: 3

NF-2: impl Deref for Item

---

Cargo.lock
crates/storage/Cargo.toml
crates/storage/src/key.rs
crates/types/src/math/signed.rs
crates/types/src/math/udec.rs

Based on https://github.com/left-curve/grug/pull/118#issuecomment-2307173322: 4

NF-3: impl PrimaryKeys and Prefix for Signed and Dec

---

crates/vm/wasm/src/gatekeeper.rs

T-WasmVm-3: Gatekeeper

---

crates/vm/wasm/src/environment.rs
crates/vm/wasm/src/vm.rs

T-WasmWm-5: Enviroment

---

crates/vm/wasm/src/lib.rs
crates/vm/wasm/src/limiting_tunables.rs
crates/vm/wasm/src/tunables.rs
crates/vm/wasm/src/vm.rs

Ref: https://github.com/left-curve/grug/issues/40

Limiting tunables

---

Cargo.lock
dango/genesis/examples/build_genesis.rs
dango/genesis/src/lib.rs
dango/testing/Cargo.toml
dango/testing/benches/benchmarks.rs
dango/testing/src/account.rs
dango/testing/src/setup.rs
grug/db-disk/Cargo.toml
grug/db-disk/src/db.rs
grug/db-disk/src/lib.rs
grug/db-disk/src/testing.rs
grug/testing/src/builder.rs
grug/testing/src/suite.rs
grug/types/src/result.rs
grug/vm-wasm/Cargo.toml
grug/vm-wasm/tests/tester.rs
justfile

Benchmarks performed on Apple M2 Pro.
| DB     | VM     | compiler   | send (TPS) | swap (TPS) |
| ------ | ------ | ---------- | ---------- | ---------- |
| DiskDb | WasmVm | singlepass | 1,712      | 648        |

test: benchmarks for TPS measurement

---

grug/app/src/app.rs
grug/app/src/execute.rs
grug/types/src/tx.rs

feat(grug): max length for salt

---

dango/bank/src/query.rs
grug/app/src/app.rs
grug/app/src/query.rs
grug/cli/src/query.rs
grug/client/src/client.rs
grug/mock-bank/src/exports.rs
grug/mock-bank/src/query.rs
grug/testing/src/suite.rs
grug/testing/tests/queries.rs
grug/types/src/bank.rs
grug/types/src/imports/querier.rs
grug/types/src/query.rs
grug/types/src/testing/querier.rs
grug/vm-wasm/src/imports.rs

refactor(grug): use singleton tuple variants for `Query`

---

Cargo.toml
docker/optimizer/Dockerfile
grug/bob-the-builder/src/main.rs
justfile

fix(grug): support wildcard workspace members in bob

---

dango/genesis/examples/build_genesis.rs
dango/genesis/src/lib.rs
dango/testing/src/setup.rs
dango/testing/tests/token_factory.rs
dango/token-factory/src/execute.rs
dango/token-factory/src/query.rs
dango/token-factory/src/state.rs
dango/types/src/token_factory.rs
docker/devnet/Dockerfile
docker/optimizer/Dockerfile

feat(dango): make denom creation fee optional

---

dango/testing/src/account.rs
dango/testing/tests/safe.rs
grug/testing/src/suite.rs
grug/types/src/result.rs

Also some minor improvements to test suite.

test(dango): add an integration test for unauthorized voting in safe

---

dango/testing/benches/benchmarks.rs
dango/testing/tests/onboarding.rs
dango/testing/tests/safe.rs
dango/testing/tests/token_factory.rs
grug/testing/src/suite.rs
grug/testing/tests/account.rs
grug/testing/tests/cron.rs
grug/testing/tests/queries.rs
grug/testing/tests/reply.rs
grug/types/src/app.rs

solve #265.
instead to use `#[must_use]` on every function that return an Outcome, the attribute `#[must_use]` is added directly to the various `Outcome` structures

feat(grug): Outcome `must-use`

---

Cargo.lock
Cargo.toml
dango/testing/src/setup.rs
grug/app/src/abci.rs
grug/app/src/app.rs
grug/app/src/error.rs
grug/app/src/lib.rs
grug/app/src/proposal.rs
grug/app/src/traits.rs
grug/cli/src/start.rs
grug/testing/Cargo.toml
grug/testing/src/builder.rs
grug/testing/src/suite.rs
grug/testing/tests/prepare_proposal.rs

adds support for state-less, synchronous proposal preparer.
in the future, we can consider supporting stateful or async ones.

feat(grug): ABCI++ prepare proposal

---

dango/account-margin/src/execute.rs
dango/account-safe/src/execute.rs
dango/account-spot/src/execute.rs
dango/auth/src/lib.rs
dango/types/src/account.rs
grug/ffi/src/exports.rs
grug/types/src/tx.rs
grug/vm-rust/src/contract.rs
grug/vm-rust/src/traits.rs

refractor(grug): `Tx` generics

---

dango/account-margin/src/execute.rs
dango/account-safe/src/execute.rs
dango/account-spot/src/execute.rs
dango/auth/src/lib.rs
dango/types/src/account.rs
grug/ffi/src/exports.rs
grug/types/src/tx.rs
grug/vm-rust/src/contract.rs
grug/vm-rust/src/traits.rs

Reverts left-curve/left-curve#310

remove `Tx` generics (reverting #310)

---

dango/account-factory/src/execute.rs
dango/account-safe/src/execute.rs
dango/auth/src/lib.rs
dango/testing/benches/benchmarks.rs
dango/testing/src/account.rs
dango/testing/tests/onboarding.rs
grug/client/src/client.rs
grug/testing/src/account.rs
grug/testing/tests/prepare_proposal.rs
grug/types/src/tx.rs

feat(grug): `Tx` `NonEmpty` msgs

---

Cargo.lock
grug/app/Cargo.toml
grug/app/src/app.rs

fix(grug): malformed `prepare_proposal` Txs can halt the chain

---

grug/app/src/execute/instantiate.rs
grug/types/src/app.rs

in `ContractInfo` the `label` should be of `Option<Label>` type, not `Option<String>`

fix(grug): a small bug related to contract label

---

book/networks/README.md
dango/genesis/examples/build_genesis.rs
dango/testing/benches/benchmarks.rs
dango/testing/src/account.rs
dango/testing/src/setup.rs
dango/testing/tests/lending.rs
dango/testing/tests/onboarding.rs
dango/testing/tests/oracle.rs
dango/testing/tests/safe.rs
dango/testing/tests/vesting.rs

- add more test accounts
- rename `Accounts` to `TestAccounts`

test(dango): add more test accounts

---

dango/account/margin/src/execute.rs
dango/account/safe/src/execute.rs
dango/account/spot/src/execute.rs
dango/auth/src/lib.rs
dango/client/src/signer.rs
dango/testing/tests/safe.rs

closes #262 #263
replaces #267

fix(dango): safe account auth issues

---

pnpm-lock.yaml
sdk/packages/connect-kit/src/connectors/eip1193.ts
sdk/packages/connect-kit/src/connectors/passkey.ts
sdk/packages/connect-kit/src/createConfig.ts
sdk/packages/core/src/clients/signerClient.ts
sdk/packages/core/src/index.ts
sdk/packages/core/src/signers/connector.ts
sdk/packages/core/src/signers/index.ts
sdk/packages/core/src/signers/privateKey.ts
sdk/packages/core/src/signers/session.ts
sdk/packages/crypto/src/keys/secp256k1.ts
sdk/packages/react/src/hooks/useConnectorClient.ts
sdk/packages/react/src/hooks/useStorage.ts
sdk/packages/react/src/index.ts
sdk/packages/types/src/config.ts
sdk/packages/types/src/connector.ts
sdk/packages/types/src/credential.ts
sdk/packages/types/src/index.ts
sdk/packages/types/src/session.ts
sdk/packages/types/src/signature.ts
sdk/packages/types/src/signer.ts
sdk/packages/utils/src/index.ts
sdk/packages/utils/src/typedData.ts
ui/portal/src/components/AccountCreation/TransferStep.tsx
ui/portal/src/components/SendContainer.tsx
ui/shared/package.json
ui/shared/src/hooks/index.ts
ui/shared/src/hooks/useSessionKey.ts
ui/shared/src/hooks/useSigningClient.ts

feat(ui): session keys signature

---

grug/jellyfish-merkle/spec/docs/invariants.md

Found this lingering TODO when I started preparing the case study for our work. This PR resolves it (see my message in TG for more details).

Resolved lingering TODO

---

dango/genesis/src/lib.rs
dango/testing/src/hyperlane.rs
dango/testing/tests/warp.rs
dango/types/src/warp.rs
dango/warp/src/execute.rs
dango/warp/src/query.rs
dango/warp/src/state.rs

feat(dango): Warp rate-limit

---

dango/account/factory/src/execute.rs
dango/genesis/src/lib.rs
dango/testing/src/account.rs
dango/testing/tests/onboarding.rs
dango/types/src/account_factory/msg.rs
dango/types/src/account_factory/salts.rs

refactor(dango): New user salt

---

.github/workflows/rust.yml
dango/cli/src/start.rs

Fixes using `Ctrl-C` to stop the process.

Fix Ctrl-c

---

dango/account/margin/src/execute.rs
dango/dex/src/execute.rs
dango/testing/tests/dex.rs
dango/testing/tests/margin.rs
dango/types/src/dex/msgs.rs

feat(dango/dex): add `batch_update_orders` method

---

dango/account/factory/src/query.rs
dango/bank/src/query.rs
dango/bank/src/state.rs
dango/types/src/account_factory/msg.rs
dango/types/src/bank/msgs.rs

no test written yet but should be good

feat(dango): add missing query functions

---

dango/taxman/src/execute.rs
dango/testing/tests/warp.rs
dango/types/src/taxman.rs
dango/warp/src/execute.rs

closes: #515 
use the taxman contract, instead of hyperlane's fee hook, to handle the withdrawal fee.

refactor(dango/wrap): have taxman handle warp withdrawl fee

---

dango/bank/src/execute.rs
dango/dex/src/execute.rs
dango/types/src/bank.rs
dango/types/src/bank/events.rs
grug/macros/src/event.rs
grug/types/src/events.rs
grug/types/src/events/builder.rs
grug/types/src/events/contract_event.rs
grug/types/src/response.rs

refractor(dango + grug): Bank events

---

dango/cli/src/start.rs
dango/httpd/src/server.rs
dango/testing/src/setup.rs
grug/testing/tests/httpd.rs
grug/testing/tests/indexing.rs
indexer/httpd/src/context.rs
indexer/httpd/src/routes.rs
indexer/httpd/src/routes/api.rs
indexer/httpd/src/routes/api/blocks.rs
indexer/httpd/src/server.rs
indexer/sql/src/block_to_index.rs
indexer/sql/src/indexer_path.rs
indexer/sql/src/lib.rs
indexer/sql/src/non_blocking_indexer.rs
indexer/testing/src/lib.rs

Add httpd endpoint for `/api/blocks/<block_height>` and `/api/block_results/<block_height>`

Add API endpoint to fetch block and block results

---

ui/applets/kit/src/components/foundation/AccountSearchInput.tsx

feat(ui): account search input

---

sdk/dango/src/utils/formatters.ts
ui/portal/web/src/app.provider.tsx
ui/portal/web/src/components/create-account/CreateAccountDepositStep.tsx
ui/portal/web/src/components/foundation/AccountCard.tsx
ui/portal/web/src/components/foundation/AccountMenu.tsx
ui/portal/web/src/components/foundation/AssetCard.tsx
ui/portal/web/src/components/modals/ConfirmAccount.tsx
ui/portal/web/src/components/modals/ConfirmSend.tsx
ui/portal/web/src/components/overview/AssetsSection.tsx
ui/portal/web/src/components/overview/SwippeableAccountCard.tsx
ui/portal/web/src/pages/(app)/_app.send-and-receive.tsx
ui/portal/web/src/pages/(app)/_app.settings.lazy.tsx
ui/store/src/connectors/eip1193.ts
ui/store/src/connectors/passkey.ts
ui/store/src/connectors/session.ts
ui/store/src/hooks/usePrices.ts
ui/store/src/hooks/useSessionKey.ts
ui/store/src/hooks/useStorage.ts

This branch fix: LEF-59, LEF-68 and LEF-11

fix(ui): format number

---

sdk/dango/src/utils/typedData.ts

fix(ui): metamask new version

---

sdk/dango/src/actions/indexer/indexerActions.ts
sdk/dango/src/actions/indexer/queryBlock.ts
ui/portal/web/src/components/explorer/BlockExplorer.tsx

feat(ui): future block explorer

---

ui/portal/web/applets.ts
ui/portal/web/src/components/foundation/AccountMenu.tsx
ui/portal/web/src/components/overview/AssetsSection.tsx
ui/portal/web/src/components/overview/WelcomeSection.tsx
ui/portal/web/src/pages/(app)/_app.transfer.lazy.tsx
ui/portal/web/src/pages/(app)/_app.transfer.tsx

feat(ui): mask to input in transfer
